name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Download the fonts
        run: for i in simhei.ttf simkai.ttf simsun.ttc simsunb.ttf simfang.ttf; do wget -P fonts/ https://xugr.keybase.pub/static/fonts/$i; done
      - name: Build font information caches
        run: fc-cache -rv
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: report.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode